# documentation: https://github.com/hyperfy-xyz/hyperfy
# slogan: A Standalone persistent world hosted on your own domain!
# tags: ThreeJS,NODE,Hyperfy,Metaverse,Self-Hosted
# logo: svgs/hyperfy.svg
# port: 3011
version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - DOMAIN=$DOMAIN
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - ADMIN_CODE=$ADMIN_CODE
      - PUBLIC_WS_URL=http://${DOMAIN}:${PORT}/ws
      - PUBLIC_API_URL=http://${DOMAIN}:${PORT}/api
      - PUBLIC_ASSETS_URL=http://${DOMAIN}:${PORT}/assets
    volumes:
      - ./data:/app/data
    restart: unless-stopped 