# documentation: https://github.com/hyperfy-xyz/hyperfy
# slogan: A Standalone persistent world hosted on your own domain!
# tags: ThreeJS,NODE,Hyperfy,Metaverse,Self-Hosted
# logo: svgs/logo-icon.svg
# port: 3000
# twitter:card: summary_large_image
# twitter:title: Hyperfy Self-Hosted World
# twitter:description: Deploy your own persistent 3D world with Hyperfy - a standalone metaverse platform
# twitter:image: https://raw.githubusercontent.com/hyperfy-xyz/hyperfy/main/public/images/preview.png
version: '3.8'
services:
  hyperfy:
    image: howieduhzit/hyperfy:main
    ports:
      - ${PORT}
    volumes:
      - ./data:/app/data
    environment:
      - DOMAIN=$DOMAIN
      - PORT=$PORT
      - ASSETS_DIR=/world/assets
      - PUBLIC_WS_URL=https://${DOMAIN}/ws
      - PUBLIC_API_URL=https://${DOMAIN}/api
      - PUBLIC_ASSETS_URL=https://${DOMAIN}/assets
      
      
    restart: unless-stopped 