version: '3.8'

services:
  hyperfy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=production
    restart: unless-stopped 