# documentation: https://github.com/hyperfy-xyz/hyperfy
# slogan: A Standalone persistent world hosted on your own domain!
# tags: ThreeJS,NODE,Hyperfy,Metaverse,Self-Hosted
# logo: svgs/logo-icon.svg
# port: 3000
# twitter:card: summary_large_image
# twitter:title: Hyperfy Self-Hosted World
# twitter:description: Deploy your own persistent 3D world with Hyperfy - a standalone metaverse platform
# twitter:image: https://raw.githubusercontent.com/hyperfy-xyz/hyperfy/main/public/images/preview.png
version: '3.8'
services:
  hyperfy:
    image: howieduhzit/hyperfy:main
    ports:
      - ${PORT}
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - ADMIN_CODE=$ADMIN_CODE
      - PUBLIC_WS_URL=http://0.0.0.0:3000/ws
      - PUBLIC_API_URL=http://0.0.0.0:3000/api
      - PUBLIC_ASSETS_URL=http://0.0.0.0:3000/assets
      
    restart: unless-stopped 