# documentation: https://github.com/hyperfy-xyz/hyperfy
# slogan: A Standalone persistent world hosted on your own domain!
# tags: ThreeJS,NODE,Hyperfy,Metaverse,Self-Hosted
# logo: svgs/logo-icon.svg
# port: 3011
version: '3.8'

services:
  hyperfy:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
      - "1337:1337"
    volumes:
      - ./data:/app/data
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=production
    restart: unless-stopped 